creat functions

diff --git a/music-finder b/music-finder
--- a/music-finder
+++ b/music-finder
@@ -18,49 +18,6 @@ orange="$(printf '\033[0;33m')"       # orange
 blue="$(printf '\033[0;34m')"         # blue
 white="$(printf '\033[0;37m')"        # white
 
-# ----------\Select directory function\----------
-function choose_dir() {
-	clear
-
-	echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${normal}"
-	echo -e "${orange}Please Select your path ${normal}"
-
-	read -p "Do you like to serach all of your system (Requires root access)? [Y/n] " searchAllSystem
-
-	if [[ "$searchAllSystem" == "" || "$searchAllSystem" == "y" || "$searchAllSystem" == "Y" ]]; then
-		# Search all of file system
-	    echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${normal}"
-	    echo -e "This operation may take a while!"
-
-		find_function "/"
-	elif [[ "$searchAllSystem" == "n" || "$searchAllSystem" == "N" ]]; then
-		read -p "Do you like search this directory? [Y/n] " likedirectory
-
-		if [[ "$likedirectory" == "" || "$likedirectory" == "y" || "$likedirectory" == "Y" ]]; then
-			# Search current directory
-		    echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${normal}"
-
-			find_function "$PWD"
-		elif [[ "$likedirectory" == "n" || "$likedirectory" == "N" ]]; then
-			# Search entered path
-			read -p "Enter a directory : " -i "" -e userEnteredDirectory
-			echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${normal}"
-				if [[ "$userEnteredDirectory" == "/" ]]; then
-					echo -e "${red}You have to chose first option :)${normal}"
-				else
-					find_function "$userEnteredDirectory"
-				fi
-		else
-			echo -e "${red}Invalid argument!${normal}"
-			exit 1
-		fi
-	else
-	    echo -e "${red}Invalid argument!${normal}"
-		exit 1
-	fi
-	echo -e "${green}\ndone!${normal}"
-}
-
 # ----------\Play musics in list of directories function\----------
 function play_in_dir() {
 	directories="$1"
@@ -130,6 +87,49 @@ function find_function() {
 		echo -e "${red}Your type is not true!${normal}"
 		exit 1
 	fi
+}
+
+# ----------\Select directory function\----------
+function choose_dir() {
+	clear
+
+	echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${normal}"
+	echo -e "${orange}Please Select your path ${normal}"
+
+	read -p "Do you like to serach all of your system (Requires root access)? [Y/n] " searchAllSystem
+
+	if [[ "$searchAllSystem" == "" || "$searchAllSystem" == "y" || "$searchAllSystem" == "Y" ]]; then
+		# Search all of file system
+	    echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${normal}"
+	    echo -e "This operation may take a while!"
+
+		find_function "/"
+	elif [[ "$searchAllSystem" == "n" || "$searchAllSystem" == "N" ]]; then
+		read -p "Do you like search this directory? [Y/n] " likedirectory
+
+		if [[ "$likedirectory" == "" || "$likedirectory" == "y" || "$likedirectory" == "Y" ]]; then
+			# Search current directory
+		    echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${normal}"
+
+			find_function "$PWD"
+		elif [[ "$likedirectory" == "n" || "$likedirectory" == "N" ]]; then
+			# Search entered path
+			read -p "Enter a directory : " -i "" -e userEnteredDirectory
+			echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${normal}"
+				if [[ "$userEnteredDirectory" == "/" ]]; then
+					echo -e "${red}You have to chose first option :)${normal}"
+				else
+					find_function "$userEnteredDirectory"
+				fi
+		else
+			echo -e "${red}Invalid argument!${normal}"
+			exit 1
+		fi
+	else
+	    echo -e "${red}Invalid argument!${normal}"
+		exit 1
+	fi
+	echo -e "${green}\ndone!${normal}"
 }
 
 # ----------\Uninstall function\----------
