add uninstall function

diff --git a/music-finder b/music-finder
--- a/music-finder
+++ b/music-finder
@@ -12,6 +12,7 @@ clear
 GRE='\033[92m' # Green Light
 RD='\033[91m' # Red Light
 
+# ----------\Main function\----------
 function main(){
 	echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
 	echo "Please Select your path "
@@ -19,7 +20,7 @@ function main(){
 	read -p "Do you like to serach all in of system (Requires root access)? [Y/n] " all_system
 
 	if [[ "$all_system" == "" || "$all_system" == "y" || "$all_system" == "Y" ]]; then
-		# ==========\Search all of file system\==========
+		# ----------\Search all of file system\----------
 	    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
 	    echo "This operation may take a while!"
 
@@ -38,7 +39,7 @@ function main(){
 		read -p "Do you like search this directory? [Y/n] " likedirectory
 
 		if [[ "$likedirectory" == "" || "$likedirectory" == "y" || "$likedirectory" == "Y" ]]; then
-			# ==========\Search current directory\==========
+			# ----------\Search current directory\----------
 		    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
 
 		    read -p "Please enter the name of music wich you search : " name
@@ -53,7 +54,7 @@ function main(){
 		        echo -e "${RD}Your type is not true!"
 		    fi
 		elif [[ "$likedirectory" == "n" || "$likedirectory" == "N" ]]; then
-			# ==========\Search entered path\==========
+			# ----------\Search entered path\----------
 			read -p "Enter a directory : " -i "" -e addressdirectory 
 		    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
 
@@ -77,6 +78,54 @@ function main(){
 	echo -e "${GRE}done!"
 }
 
+# ----------\Uninstall function\----------
+function uninstall(){
+	clear
+
+	GRE='\033[92m' # Green Light
+	RD='\033[91m' # Red Light
+
+	read -p "Are you sure to uninstall music-finder??!! [y/N] " delete
+
+	# ----------\Uninstall music-finder\---------
+	if [[ "$delete" == "y" || "$delete" == "Y" ]]; then
+		del_dependes=0
+		#Checking if the distro is debianbase / archbase / redhatbase/ openSUSEbase and running the correct command
+		codename="lsb_release -c | awk {'print $2'}"
+		architecture="dpkg --print-architecture"
+		if pacman -Q &> /dev/null; then # Check Arch
+			sudo pacman -Rs mplayer
+		elif [[ "$codename" == "bionic" ]] && [[ "$architecture" == "armhf" ]]; then # Check Ubuntu Server and raspberry
+			sudo apt remove mplayer
+		elif apt list --installed &> /dev/null; then # Check Debian
+			sudo apt remove mplayer
+		elif dnf list &> /dev/null; then # Check Fedora
+			sudo dnf remove mplayer
+		elif zypper search i+ &> /dev/null; then # Check openSUSE
+			sudo zypper remove mplayer
+		else
+			echo -e "${RD}Your distro is neither archbase nor debianbase nor redhatbase nor susebase So, The script is not going to work in your distro and you have uninstall the dependensies manually. for more information read README.md"
+			del_dependes="1"
+		fi
+
+		sudo rm -f /usr/bin/music-finder
+		# ----------\Removing Music-finder Command\----------
+		if [[ "$del_dependes" == "0" ]]; then
+		# bug : if user doesnt enter password script print music-finder succesfully uninstalled
+		    echo -e "\n ${RD}music-finder succesfully uninstalled :( "
+		else
+			exit 1
+		fi
+	elif [[ "$delete" == "" || "$delete" == "n" || "$delete" == "N" ]]; then
+		echo -e "\n ${GRE}music-finder is still installed :) "
+		exit 0
+	else
+		echo -e "${RD}Invalid argument!"
+		exit 1
+	fi
+}
+
+# ----------\Update fiunction\----------
 function update(){
 if [ -d "$HOME/.config/Music_Finder/" ];then
     cd $HOME/.config/Music_Finder/
@@ -90,8 +139,10 @@ else
 fi
 }
 
+# --------\Input options\--------
 case "$1" in
     "")    main    ;;
     "--update" | "-U")    update    ;;
+	"--uninstall")    uninstall    ;;
 esac
 exit 0
