make main function

diff --git a/music-finder b/music-finder
--- a/music-finder
+++ b/music-finder
@@ -2,7 +2,7 @@
 
 
 #################################################################
-#                        Music_Finder V1.2                      #
+#                        Music_Finder V1.1                      #
 #  https://gitlab.com/hessam.ashari/Search_Music_and_Playe.git  #
 #################################################################
 
@@ -12,65 +12,86 @@ clear
 GRE='\033[92m' # Green Light
 RD='\033[91m' # Red Light
 
-echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
-echo "Please Select your path "
+function main(){
+	echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
+	echo "Please Select your path "
 
-read -p "Do you like to serach all in of system (Requires root access)? [Y/n] " all_system
+	read -p "Do you like to serach all in of system (Requires root access)? [Y/n] " all_system
 
-if [[ "$all_system" == "" || "$all_system" == "y" || "$all_system" == "Y" ]]; then
-	# ==========\Search all of file system\==========
-    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
-    echo "This operation may take a while!"
-
-    read -p "Please enter the name of music wich you search : " name
-    read -p "Please Select your type d {directory} f {file} : " typelike
-
-    if [[ $typelike == "d" ]]; then
-        sudo find  / -type d -name  $name
-    elif [[ $typelike == "f" ]]; then
-        echo "Install the mplayer if you want tp play music after find it"
-        sudo find / -type f -name "*$name*" -exec mplayer {} \;
-    else
-        echo -e "${RD}Your type is not true!"
-    fi
-elif [[ "$all_system" == "n" || "$all_system" == "N" ]]; then
-	read -p "Do you like search this directory? [Y/n] " likedirectory
-
-	if [[ "$likedirectory" == "" || "$likedirectory" == "y" || "$likedirectory" == "Y" ]]; then
-		# ==========\Search current directory\==========
+	if [[ "$all_system" == "" || "$all_system" == "y" || "$all_system" == "Y" ]]; then
+		# ==========\Search all of file system\==========
 	    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
+	    echo "This operation may take a while!"
 
 	    read -p "Please enter the name of music wich you search : " name
 	    read -p "Please Select your type d {directory} f {file} : " typelike
 
 	    if [[ $typelike == "d" ]]; then
-	        find  $PWD -type d -name  $name
+	        sudo find  / -type d -name  $name
 	    elif [[ $typelike == "f" ]]; then
 	        echo "Install the mplayer if you want tp play music after find it"
-	        find  $PWD -type f -name "*$name*" -exec mplayer {} \;
+	        sudo find / -type f -name "*$name*" -exec mplayer {} \;
 	    else
 	        echo -e "${RD}Your type is not true!"
 	    fi
-	elif [[ "$likedirectory" == "n" || "$likedirectory" == "N" ]]; then
-		# ==========\Search entered path\==========
-		read -p "Enter a directory : " -i "" -e addressdirectory 
-	    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
+	elif [[ "$all_system" == "n" || "$all_system" == "N" ]]; then
+		read -p "Do you like search this directory? [Y/n] " likedirectory
 
-	    read -p "Please enter the name of music wich you search : " name
-	    read -p "Please Select your type d {directory} f {file} : " liketype
+		if [[ "$likedirectory" == "" || "$likedirectory" == "y" || "$likedirectory" == "Y" ]]; then
+			# ==========\Search current directory\==========
+		    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
 
-	    if [[ $liketype == "d" ]]; then
-	        find $addressdirectory -type d -iname $name
-	    elif [[ $liketype == "f" ]]; then
-	        echo "Install the mplayer if you want tp play music after find it"
-	        find $addressdirectory -type f -iname "*$name*" -exec mplayer {} \;
-	    else
-	        echo -e "${RD}Your type is not true!"
-	    fi
+		    read -p "Please enter the name of music wich you search : " name
+		    read -p "Please Select your type d {directory} f {file} : " typelike
+
+		    if [[ $typelike == "d" ]]; then
+		        find  $PWD -type d -name  $name
+		    elif [[ $typelike == "f" ]]; then
+		        echo "Install the mplayer if you want tp play music after find it"
+		        find  $PWD -type f -name "*$name*" -exec mplayer {} \;
+		    else
+		        echo -e "${RD}Your type is not true!"
+		    fi
+		elif [[ "$likedirectory" == "n" || "$likedirectory" == "N" ]]; then
+			# ==========\Search entered path\==========
+			read -p "Enter a directory : " -i "" -e addressdirectory 
+		    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
+
+		    read -p "Please enter the name of music wich you search : " name
+		    read -p "Please Select your type d {directory} f {file} : " liketype
+
+		    if [[ $liketype == "d" ]]; then
+		        find $addressdirectory -type d -iname $name
+		    elif [[ $liketype == "f" ]]; then
+		        echo "Install the mplayer if you want tp play music after find it"
+		        find $addressdirectory -type f -iname "*$name*" -exec mplayer {} \;
+		    else
+		        echo -e "${RD}Your type is not true!"
+		    fi
+		else
+			echo -e "${RD}Invalid argument!"
+		fi
 	else
-		echo -e "${RD}Invalid argument!"
+	    echo -e "${RD}Invalid argument!"
 	fi
+	echo -e "${GRE}done!"
+}
+
+function update(){
+if [ -d "$HOME/.config/Music_Finder/" ];then
+    cd $HOME/.config/Music_Finder/
+    git pull
+    sleep 2
+    sudo cp music-finder /usr/bin/music-finder
+    sudo chmod 755 /usr/bin/music-finder
 else
-    echo -e "${RD}Invalid argument!"
+    echo -e " ${RD}Config Error ! "
+    exit 1
 fi
-echo -e "${GRE}done!"
+}
+
+case "$1" in
+	"") 	main 	;;
+	"--update" | "-U")	   update  ;;
+esac
+exit 0
