fix bugs

diff --git a/music-finder b/music-finder
--- a/music-finder
+++ b/music-finder
@@ -47,6 +47,7 @@ function play_in_dir() {
 # ----------\Find music function\----------
 function find_function() {
 	local inputDir="$1"
+
 	read -p "Please enter the name of music wich you search : " name
 	read -p "Please Select your type d {directory} f {file} : " selectedType
 
@@ -198,57 +199,34 @@ function uninstall() {
 function update() {
 	clear
 
+	# Check place of repo for existing files
 	if [[ -d /tmp/music-finder/ ]]; then
 		sudo rm -rf /tmp/music-finder/
-		# Check access of /tmp
-		if cd /tmp/ &> /dev/null; then
-			git clone https://github.com/hessamashari/music-finder.git /tmp/music-finder
-			sleep 2
-			# Check access of /tmp/music-finder
-			if cd /tmp/music-finder/ &> /dev/null; then
-				# Replace older program with newer
-				sudo cp /tmp/music-finder/music-finder /usr/bin/music-finder
-				sudo chmod 755 /usr/bin/music-finder
-				# Check operation
-				if [[ "$?" == "0" ]]; then
-					echo -e " ${green}Music_Finder updated succesfully! ${normal}"
-				else
-					echo -e " ${red}Music_Finder doesn't update succesfully! ${normal}"
-					exit 1
-				fi
+	fi
+
+	# Check access of /tmp
+	if cd /tmp/ &> /dev/null; then
+		git clone https://github.com/hessamashari/music-finder.git /tmp/music-finder
+		sleep 2
+		# Check access of /tmp/music-finder
+		if cd /tmp/music-finder/ &> /dev/null; then
+			# Replace older program with newer
+			sudo cp /tmp/music-finder/music-finder /usr/bin/music-finder
+			sudo chmod 755 /usr/bin/music-finder
+			# Check operation
+			if [[ "$?" == "0" ]]; then
+				echo -e " ${green}Music_Finder updated succesfully! ${normal}"
 			else
-				echo -e "${red}\nCannot cd to directory ${orange}'/tmp/music-finder'${normal}"
+				echo -e " ${red}Music_Finder doesn't update succesfully! ${normal}"
 				exit 1
 			fi
 		else
-			echo -e "${red}\nCannot cd to directory ${orange}'/tmp'${normal}"
+			echo -e "${red}\nCannot cd to directory ${orange}'/tmp/music-finder'${normal}"
 			exit 1
 		fi
 	else
-		if cd /tmp/ &> /dev/null; then
-			# Check access of /tmp
-			git clone https://github.com/hessamashari/music-finder.git /tmp/music-finder
-			sleep 2
-			# Check access of /tmp/music-finder
-			if cd /tmp/music-finder/ &> /dev/null; then
-				# Replace older program with newer
-				sudo cp /tmp/music-finder/music-finder /usr/bin/music-finder
-				sudo chmod 755 /usr/bin/music-finder
-				# Check operation
-				if [[ "$?" == "0" ]]; then
-					echo -e " ${green}Music_Finder updated succesfully! ${normal}"
-				else
-					echo -e " ${red}Music_Finder doesn't update succesfully! ${normal}"
-					exit 1
-				fi
-			else
-				echo -e "${red}\nCannot cd to directory ${orange}'/tmp/music-finder'${normal}"
-				exit 1
-			fi
-		else
-			echo -e "${red}\nCannot cd to directory ${orange}'/tmp'${normal}"
-			exit 1
-		fi
+		echo -e "${red}\nCannot cd to directory ${orange}'/tmp'${normal}"
+		exit 1
 	fi
 
 	# Delet cloned repository
